spring.application.name=backend

# DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/cathori
spring.datasource.username=cathori
spring.datasource.password=cathori1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.cathori.backend=DEBUG


gemini.api.key = AIzaSyBUD6Uss6owln8g1vjXBvkKqTIr3j2ZC5I

# SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=leegeebark@gmail.com
spring.mail.password=etetiwwptgiswjla
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT
jwt.secret-key=Y2F0aG9yaVNlY3JldEtleUZvckpXVEF1dGhlbnRpY2F0aW9uMjAyNg==
jwt.access-token-expiry=3600000
jwt.refresh-token-expiry=2592000000
