# App Info
spring.application.name=${APP_NAME}

# DataSource
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER}

# JPA
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO}
spring.jpa.show-sql=${JPA_SHOW_SQL}
spring.jpa.properties.hibernate.format_sql=${JPA_FORMAT_SQL}
logging.level.org.cathori.backend=${LOGGING_LEVEL_CATHORI}

# Gemini API Key
gemini.api.key=${GEMINI_API_KEY}

# SMTP
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=${MAIL_SMTP_AUTH}
spring.mail.properties.mail.smtp.starttls.enable=${MAIL_STARTTLS_ENABLE}

# JWT
jwt.secret-key=${JWT_SECRET_KEY}
jwt.access-token-expiry=${JWT_ACCESS_TOKEN_EXPIRY}
jwt.refresh-token-expiry=${JWT_REFRESH_TOKEN_EXPIRY}

# ALRAM
crawler.dispatch.cron=0 0 */1 * * *
alert.dispatch.cron=0 */2 * * * *

# Firebase
firebase.credential.path=${FIREBASE_CREDENTIAL_PATH}
